# Generated by Django 3.2.23 on 2023-12-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidjangoprject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userlists',
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='events',
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Userlist',
        ),
    ]
