# Generated by Django 3.2.23 on 2023-12-04 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='status',
        ),
    ]
